name: iguazu-env
channels:
  - defaults
  - conda-forge
dependencies:
  # Python dependencies
  - python>=3.7
  - bokeh>=1.3,<2.0
  - colorlog>=4.0,<5.0
  - click>=7.0,<8.0
  - docker-py>=4.0,<5.0
  - numpy>=1.16,<2.0
  - pandas>=0.25.0,<0.26.0
  - psutil>=5.6.3,<5.7
  - scikit-learn>=0.21.2,<0.22.0
  - scipy>=1.3,<2.0
  - simplegeneric>=0.8.1,<0.9.0
  - scikit-learn>=0.21.2,<0.22.0
  - statsmodels>=0.10.1,<0.11
  - pytables>=3.5,<4.0
  - tzlocal>=2.0,<3.0
  - pip
  - pip:
    - graphviz>=0.11.1<0.12.0
    - prefect>=0.6.1,<0.6.2
    - git+https://github.com/quetz-al/quetzal-client@v0.3.0#egg=quetzal-client
    - git+https://github.com/quetz-al/quetzal-openapi-client@v0.3.0#egg=quetzal-openapi-client
    - git+https://github.com/OpenMindInnovation/datascience_utils@v0.3.0#egg=dsu
