name: iguazu-env
channels:
  - defaults
  - omind
  - conda-forge
dependencies:
  # Python dependencies
  - python>=3.7
  - bokeh>=1.3,<2.0
  - colorlog>=4.0,<5.0
  - click>=7.0,<8.0
  - docker-py>=4.0,<5.0
  - numpy>=1.16,<2.0
  - mne>=0.19.2,<0.20
  - pandas>=0.25.0,<0.26.0
  - psutil>=5.6.3,<5.7
  - scikit-learn>=0.21.2,<0.22.0
  - scipy>=1.3,<2.0
  - simplegeneric>=0.8.1,<0.9.0
  - scikit-learn>=0.21.2,<0.22.0
  - statsmodels>=0.10.1,<0.11
  - pytables>=3.5,<4.0
  - tzlocal>=2.0,<3.0
  - dsu>=0.3.0,<0.4
  # Note on pyyaml: it is important to avoid pyyaml version 5.2, because it is
  # incompatible with a conda + pip package mix: dsu, and possibly other conda
  # packages require pyyaml, and at the same time prefect and quetzal-client
  # (which are pip packages) require pyyaml too. They way pyyaml is distributed
  # makes it fail when pip and conda are mixed. This does not happen on previous
  # versions of pyyaml.
  - pyyaml>=5.1.2,<5.2
  - pip
  - pip:
    - graphviz>=0.11.1,<0.12.0
    - prefect>=0.6.1,<0.6.2
    - quetzal-client>=0.5.0,<0.6
