name: iguazu-env
channels:
  - defaults
  - conda-forge
dependencies:
  # Python dependencies
  - python>=3.7
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - pytables
  - tzlocal
  - simplegeneric
  - click
  - prefect==0.6
  - docker-py
  - pip
  - pip:
    - APScheduler
    - graphviz
    - git+https://github.com/quetz-al/quetzal-client.git@268b5f9#egg=quetzal-client
    - git+https://github.com/OpenMindInnovation/datascience_utils.git@v0.3.0#egg=dsu
