apiVersion: v1
name: iguazu
version: 0.1.0     # Chart version
appVersion: 0.1.0  # Iguazu app version
description: A Helm chart for an Iguazu cluster
# home: https://our-site.omind.me
maintainers:
  - name: David Ojeda
    email: david@omind.me
  - name: Raphaëlle Betrand-Lalo
    email: raphaelle@omind.me
