# Default values for iguazu.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

iguazu:
  # Use these as the default repository and tag
  repository: eu.gcr.io/quetzal-omind/iguazu/iguazu
  tag: 0.1.1

jobs:
  # Define one entry per cron job.
  # Note that schedule is defined in cron format. Here is a cheatsheet:
  #  ┌───────────────────── minute (0 - 59)
  #  │ ┌─────────────────── hour (0 - 23)
  #  │ │ ┌───────────────── day of the month (1 - 31)
  #  │ │ │ ┌─────────────── month (1 - 12)
  #  │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday;
  #  │ │ │ │ │                                   7 is also Sunday on some systems)
  # "* * * * *"
  #
  # Example: "1 0 * * *" is every day at one minute past midnight
  #          "*/5 * * * *" is every five minutes
  #          "45 23 * * 6" is every saturday at 23:45
  #
  ##############################################################################
  # Galvanic features
  - name: galvanic-features
    image:
      # repository: ... # use to override the default on iguazu.repository
      # tag: ...        # use to override the default on iguazu.tag
      pullPolicy: Always
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    startingDeadlineSeconds: 15
    restartPolicy: Never
    concurrencyPolicy: Forbid   # Only once at a time!
    schedule: "0 18 * * *"      # In human: every day at exactly 18h
    suspend: false              # Put this on true to suspend this task
    args: ["iguazu",
           # General iguazu options
           "--log-level", "DEBUG",
           # Action
           "flows", "run",
           # Action options
           "--executor-type", "dask",
           "--executor-address", "dask-scheduler:8786",
           # Flow name
           "galvanic_features",
           # Flow options
           "--data-source", "quetzal",
           "--workspace-name", "$(IGUAZU_WORKSPACE)",
           #"--limit", "100", "--shuffle",
           ]

    env:
      - name: PYTHONUNBUFFERED
        value: "1"
      - name: QUETZAL_URL
        value: "https://quetzal.omind.me/api/v1"
      - name: QUETZAL_INSECURE
        value: "0"
      - name: IGUAZU_WORKSPACE
        value: "iguazu-features-v011"
    envFromSecret:
      - name: QUETZAL_USER
        key: username
      - name: QUETZAL_PASSWORD
        key: password
      - name: SLACK_WEBHOOK_URL
        key: slack_url
    resources:
      limits:
        cpu: 50m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 256Mi
  ##############################################################################
  # Behavioral features
  - name: behavior-features
    image:
      # repository: ... # use to override the default on iguazu.repository
      # tag: ...        # use to override the default on iguazu.tag
      pullPolicy: Always
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    startingDeadlineSeconds: 15
    restartPolicy: Never
    concurrencyPolicy: Forbid   # Only once at a time!
    schedule: "0 16 * * *"      # In human: every day at exactly 16h
    suspend: false              # Put this on true to suspend this task
    args: ["iguazu",
           # General iguazu options
           "--log-level", "DEBUG",
           # Action
           "flows", "run",
           # Action options
           "--executor-type", "dask",
           "--executor-address", "dask-scheduler:8786",
           # Flow name
           "behavior_features",
           # Flow options
           "--data-source", "quetzal",
           "--workspace-name", "$(IGUAZU_WORKSPACE)",
           #"--limit", "100", "--shuffle",
           ]

    env:
      - name: PYTHONUNBUFFERED
        value: "1"
      - name: QUETZAL_URL
        value: "https://quetzal.omind.me/api/v1"
      - name: QUETZAL_INSECURE
        value: "0"
      - name: IGUAZU_WORKSPACE
        value: "iguazu-features-v011"
    envFromSecret:
      - name: QUETZAL_USER
        key: username
      - name: QUETZAL_PASSWORD
        key: password
      - name: SLACK_WEBHOOK_URL
        key: slack_url
    resources:
      limits:
        cpu: 50m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 256Mi


dask_scheduler:
  name: dask-scheduler
  image:
    # repository: ... # use to override the default on iguazu.repository
    # tag: ...        # use to override the default on iguazu.tag
    pullPolicy: Always
  replicas: 1
  serviceType: ClusterIP  # Change to LoadBalancer if you want to access from outside (this is dangerous!)
  servicePort: 8786
  env:
    - name: PYTHONUNBUFFERED
      value: "1"
  resources: {}
    # limits:
    #   cpu: 1.8
    #   memory: 6G
    # requests:
    #   cpu: 1.8
    #   memory: 6G
  tolerations: []
  nodeSelector: {}
  affinity: {}

dask_worker:
  name: dask-worker
  image:
    # repository: ... # use to override the default on iguazu.repository
    # tag: ...        # use to override the default on iguazu.tag
    pullPolicy: Always
  replicas: 2         # Number of MINIMUM dask-workers
  maxReplicas: 12     # Number of MAXIMUM dask-workers
  targetCPU: 10
  aptPackages: >-
  default_resources:  # overwritten by resource limits if they exist
    cpu: 1
    memory: "2GiB"
  env:
    - name: PYTHONUNBUFFERED
      value: "1"
  resources:
     limits:
       cpu: 1     # note: use integer (round values) here
       memory: 4G
     requests:
       cpu: 1
       memory: 4G
  tolerations: []
  nodeSelector: {}
  affinity: {}

quetzal:
  # Set these values with the URL, username and password used
  url: https://quetzal.omind.me/api/v1
  username: iguazu
  password:
  insecure: "0"

slack:
  url: "https://hooks.slack.com/services/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"
