# Default values for iguazu.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#replicaCount: 1
#
#image:
#  repository: nginx
#  tag: stable
#  pullPolicy: IfNotPresent
#
#imagePullSecrets: []
#nameOverride: ""
#fullnameOverride: ""
#
#service:
#  type: ClusterIP
#  port: 80
#
#ingress:
#  enabled: false
#  annotations: {}
#    # kubernetes.io/ingress.class: nginx
#    # kubernetes.io/tls-acme: "true"
#  hosts:
#    - host: chart-example.local
#      paths: []
#
#  tls: []
#  #  - secretName: chart-example-tls
#  #    hosts:
#  #      - chart-example.local
#
#resources: {}
#  # We usually recommend not to specify default resources and to leave this as a conscious
#  # choice for the user. This also increases chances charts run on environments with little
#  # resources, such as Minikube. If you do want to specify resources, uncomment the following
#  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
#  # limits:
#  #   cpu: 100m
#  #   memory: 128Mi
#  # requests:
#  #   cpu: 100m
#  #   memory: 128Mi
#
#nodeSelector: {}
#
#tolerations: []
#
#affinity: {}

scheduler:
  name: scheduler
  image:
    repository: eu.gcr.io/quetzal-omind/iguazu/iguazu
    tag: 0.0.3
    pullPolicy: Always
  replicas: 1
  resources: {}
    # limits:
    #   cpu: 1.8
    #   memory: 6G
    # requests:
    #   cpu: 1.8
    #   memory: 6G
  tolerations: []
  nodeSelector: {}
  affinity: {}
  env:
    - name: QUETZAL_URL
      value: "https://quetzal.omind.me/api/v1"
    - name: QUETZAL_INSECURE
      value: "0"
    - name: IGUAZU_WORKSPACE
      value: "iguazu-workspace-v2"

dask_scheduler:
  name: dask-scheduler
  image:
    repository: eu.gcr.io/quetzal-omind/iguazu/iguazu
    tag: 0.0.3
    pullPolicy: Always
  replicas: 1
  serviceType: "LoadBalancer"
  servicePort: 8786
  resources: {}
    # limits:
    #   cpu: 1.8
    #   memory: 6G
    # requests:
    #   cpu: 1.8
    #   memory: 6G
  tolerations: []
  nodeSelector: {}
  affinity: {}

dask_scheduler_ui:
  name: webui
  servicePort: 80

dask_worker:
  name: dask-worker
  image:
    repository: eu.gcr.io/quetzal-omind/iguazu/iguazu
    tag: 0.0.3
    pullPolicy: Always
  replicas: 2
  maxReplicas: 12
  aptPackages: >-
  default_resources:  # overwritten by resource limits if they exist
    cpu: 1
    memory: "2GiB"
  env:
    - name: PYTHONUNBUFFERED
      value: "1"
    # - name: EXTRA_CONDA_PACKAGES
    #   value: numba xarray -c conda-forge
    # - name: EXTRA_PIP_PACKAGES
    #   value: s3fs dask-ml --upgrade
  resources:
     limits:
       cpu: 1     # note: use integer (round values) here
       memory: 4G
     requests:
       cpu: 1
       memory: 4G
  tolerations: []
  nodeSelector: {}
  affinity: {}

quetzal:
  # Set these values with the URL, username and password used
  url: https://quetzal.omind.me/api/v1
  username: iguazu
  password:
  insecure: "0"

slack:
  url: "https://hooks.slack.com/services/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"
