# Default values for iguazu.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

iguazu:
  # Use these as the default repository and tag
  repository: eu.gcr.io/quetzal-omind/iguazu/iguazu
  tag: 0.3.0-dev-raph-005
  pullPolicy: Always


defaultJob:
  # All of these entries can be overriden by a particular job
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  startingDeadlineSeconds: 15
  restartPolicy: Never
  concurrencyPolicy: Forbid   # Only once at a time!
  suspend: true              # Put this on true to suspend tasks
  env:
    - name: PYTHONUNBUFFERED
      value: "1"
    - name: QUETZAL_URL
      value: "https://dev.omind.quetz.al/api/v1" # "https://quetzal.omind.me/api/v1"
    - name: QUETZAL_INSECURE
      value: "0"
    - name: IGUAZU_WORKSPACE
      value: "iguazu-vr-v1"
  envFromSecret:
    - name: QUETZAL_API_KEY
      key: api_key
    - name: SLACK_WEBHOOK_URL
      key: slack_url


  resources:
    limits:
      cpu: 50m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 256Mi
  tolerations: []
  nodeSelector: {}
  affinity: {}

jobs:
  # Define one entry per cron job.
  # required entries are:
  # name:     identifier for the job
  # args:     the command line that defines the job
  # schedule: when to run the job
  #
  # All other entries are optional and default to the defaultJob configuration
  #
  # The schedule is defined in cron format. Here is a cheatsheet:
  #  ┌───────────────────── minute (0 - 59)
  #  │ ┌─────────────────── hour (0 - 23)
  #  │ │ ┌───────────────── day of the month (1 - 31)
  #  │ │ │ ┌─────────────── month (1 - 12)
  #  │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday;
  #  │ │ │ │ │                                   7 is also Sunday on some systems)
  # "* * * * *"
  #
  # Example: "1 0 * * *" is every day at one minute past midnight
  #          "*/5 * * * *" is every five minutes
  #          "45 23 * * 6" is every saturday at 23:45
  #
  ##############################################################################
  - name: debug-sleep
    schedule: "0 21 * * *"      # In human: every day at exactly 9 pm
    # suspend: false            # Put this on true to suspend this task
    args: ["sleep",
      # General iguazu options
           "3600",
    ]
  # VR protocol standardization
  - name: standardize-vr
    # imageRepository: ...      # Use to override the default on iguazu.repository
    # imageTag: ...             # Use to override the default on iguazu.tag
    # imagePullPolicy: ..       # Use to override the default on iguazu.pullPolicy
    schedule: "0 21 * * *"      # In human: every day at exactly 9 pm
    # suspend: false            # Put this on true to suspend this task
    args: ["iguazu",
           # General iguazu options
           "--log-level", "DEBUG",
           # Action
           "flows", "run",
           # Action options
           "--executor-type", "dask",
           "--executor-address", "dask-scheduler:8786",
           "--allow-flow-failure",
           "--temp-url", "quetzal://$(IGUAZU_WORKSPACE)/temp_standard",
           "--output-url", "quetzal://$(IGUAZU_WORKSPACE)/standard",
           # Flow name
           "standardize_vr",
           # Flow options
           "--data-source", "quetzal",
           "--workspace-name", "$(IGUAZU_WORKSPACE)",
           "--limit", "50", "--shuffle",
    ]
  ##############################################################################
  # Galvanic features
  - name: galvanic-features
    # imageRepository: ...      # Use to override the default on iguazu.repository
    # imageTag: ...             # Use to override the default on iguazu.tag
    # imagePullPolicy: ..       # Use to override the default on iguazu.pullPolicy
    schedule: "0 1 * * *"       # In human: every day at exactly 1 am
    # suspend: false            # Put this on true to suspend this task
    args: ["iguazu",
           # General iguazu options
           "--log-level", "DEBUG",
           # Action
           "flows", "run",
           # Action options
           "--executor-type", "dask",
           "--executor-address", "dask-scheduler:8786",
           "--allow-flow-failure",
           "--temp-url", "quetzal://$(IGUAZU_WORKSPACE)/temp_galvanic",
           "--output-url", "quetzal://$(IGUAZU_WORKSPACE)/galvanic",
           # Flow name
           "features_galvanic",
           # Flow options
           "--data-source", "quetzal",
           "--workspace-name", "$(IGUAZU_WORKSPACE)",
           #"--limit", "100", "--shuffle",
           ]
  ##############################################################################
  # Galvanic summary
  - name: galvanic-summary
    # imageRepository: ...      # Use to override the default on iguazu.repository
    # imageTag: ...             # Use to override the default on iguazu.tag
    # imagePullPolicy: ..       # Use to override the default on iguazu.pullPolicy
    schedule: "0 13 * * *"      # In human: every day at exactly 1 pm
    # suspend: false            # Put this on true to suspend this task
    args: ["iguazu",
           # General iguazu options
           "--log-level", "DEBUG",
           # Action
           "flows", "run",
           # Action options
           "--executor-type", "dask",
           "--executor-address", "dask-scheduler:8786",
           "--allow-flow-failure",
           "--temp-url", "quetzal://$(IGUAZU_WORKSPACE)/temp_galvanic",
           "--output-url", "quetzal://$(IGUAZU_WORKSPACE)/galvanic",
           # Flow name
           "summarize_galvanic",
           # Flow options
           "--data-source", "quetzal",
           "--workspace-name", "$(IGUAZU_WORKSPACE)",
           ]
  ##############################################################################
  # Cardiac features
  - name: cardiac-features
    # imageRepository: ...      # Use to override the default on iguazu.repository
    # imageTag: ...             # Use to override the default on iguazu.tag
    # imagePullPolicy: ..       # Use to override the default on iguazu.pullPolicy
    schedule: "0 2 * * *"       # In human: every day at exactly 2 am
    # suspend: false            # Put this on true to suspend this task
    args: ["iguazu",
           # General iguazu options
           "--log-level", "DEBUG",
           # Action
           "flows", "run",
           # Action options
           "--executor-type", "dask",
           "--executor-address", "dask-scheduler:8786",
           "--allow-flow-failure",
           "--temp-url", "quetzal://$(IGUAZU_WORKSPACE)/temp_cardiac",
           "--output-url", "quetzal://$(IGUAZU_WORKSPACE)/cardiac",
           # Flow name
           "features_cardiac",
           # Flow options
           "--data-source", "quetzal",
           "--workspace-name", "$(IGUAZU_WORKSPACE)",
           #"--limit", "100", "--shuffle",
           ]
  ##############################################################################
  # Cardiac summary
  - name: cardiac-summary
    # imageRepository: ...      # Use to override the default on iguazu.repository
    # imageTag: ...             # Use to override the default on iguazu.tag
    # imagePullPolicy: ..       # Use to override the default on iguazu.pullPolicy
    schedule: "0 14 * * *"      # In human: every day at exactly 2 pm
    # suspend: false            # Put this on true to suspend this task
    args: ["iguazu",
           # General iguazu options
           "--log-level", "DEBUG",
           # Action
           "flows", "run",
           # Action options
           "--executor-type", "dask",
           "--executor-address", "dask-scheduler:8786",
           "--allow-flow-failure",
           "--temp-url", "quetzal://$(IGUAZU_WORKSPACE)/temp_cardiac",
           "--output-url", "quetzal://$(IGUAZU_WORKSPACE)/cardiac",
           # Flow name
           "summarize_cardiac",
           # Flow options
           "--data-source", "quetzal",
           "--workspace-name", "$(IGUAZU_WORKSPACE)",
           ]
  ##############################################################################
  # Behavioral features
  - name: behavior-features
    # imageRepository: ...      # Use to override the default on iguazu.repository
    # imageTag: ...             # Use to override the default on iguazu.tag
    # imagePullPolicy: ..       # Use to override the default on iguazu.pullPolicy
    schedule: "0 2 * * *"       # In human: every day at exactly 2 am
    # suspend: false            # Put this on true to suspend this task
    args: ["iguazu",
           # General iguazu options
           "--log-level", "DEBUG",
           # Action
           "flows", "run",
           # Action options
           "--executor-type", "dask",
           "--executor-address", "dask-scheduler:8786",
           "--allow-flow-failure",
           "--temp-url", "quetzal://$(IGUAZU_WORKSPACE)/temp_behavior",
           "--output-url", "quetzal://$(IGUAZU_WORKSPACE)/behavior",
           # Flow name
           "features_behavior",
           # Flow options
           "--data-source", "quetzal",
           "--workspace-name", "$(IGUAZU_WORKSPACE)",
           #"--limit", "100", "--shuffle",
           ]
  ##############################################################################
  # Behavioral summary
  - name: behavior-summary
    # imageRepository: ...      # Use to override the default on iguazu.repository
    # imageTag: ...             # Use to override the default on iguazu.tag
    # imagePullPolicy: ..       # Use to override the default on iguazu.pullPolicy
    schedule: "0 14 * * *"      # In human: every day at exactly 2 pm
    # suspend: false            # Put this on true to suspend this task
    args: ["iguazu",
           # General iguazu options
           "--log-level", "DEBUG",
           # Action
           "flows", "run",
           # Action options
           "--executor-type", "dask",
           "--executor-address", "dask-scheduler:8786",
           "--allow-flow-failure",
           "--temp-url", "quetzal://$(IGUAZU_WORKSPACE)/temp_behavior",
           "--output-url", "quetzal://$(IGUAZU_WORKSPACE)/behavior",
           # Flow name
           "summarize_behavior",
           # Flow options
           "--data-source", "quetzal",
           "--workspace-name", "$(IGUAZU_WORKSPACE)",
           ]
  ##############################################################################
  # Respiration features
  - name: respiration-features
    # imageRepository: ...      # Use to override the default on iguazu.repository
    # imageTag: ...             # Use to override the default on iguazu.tag
    # imagePullPolicy: ..       # Use to override the default on iguazu.pullPolicy
    schedule: "0 2 * * *"       # In human: every day at exactly 2 am
    # suspend: false            # Put this on true to suspend this task
    args: ["iguazu",
      # General iguazu options
           "--log-level", "DEBUG",
      # Action
           "flows", "run",
      # Action options
           "--executor-type", "dask",
           "--executor-address", "dask-scheduler:8786",
           "--allow-flow-failure",
           "--temp-url", "quetzal://$(IGUAZU_WORKSPACE)/temp_respiration",
           "--output-url", "quetzal://$(IGUAZU_WORKSPACE)/respiration",
      # Flow name
           "features_respiration",
      # Flow options
           "--data-source", "quetzal",
           "--workspace-name", "$(IGUAZU_WORKSPACE)",
      #"--limit", "100", "--shuffle",
    ]
  ##############################################################################
  # Respiration summary
  - name: respiration-summary
    # imageRepository: ...      # Use to override the default on iguazu.repository
    # imageTag: ...             # Use to override the default on iguazu.tag
    # imagePullPolicy: ..       # Use to override the default on iguazu.pullPolicy
    schedule: "0 14 * * *"      # In human: every day at exactly 2 pm
    # suspend: false            # Put this on true to suspend this task
    args: ["iguazu",
      # General iguazu options
           "--log-level", "DEBUG",
      # Action
           "flows", "run",
      # Action options
           "--executor-type", "dask",
           "--executor-address", "dask-scheduler:8786",
           "--allow-flow-failure",
           "--temp-url", "quetzal://$(IGUAZU_WORKSPACE)/temp_respiration",
           "--output-url", "quetzal://$(IGUAZU_WORKSPACE)/respiration",
      # Flow name
           "summarize_respiration",
      # Flow options
           "--data-source", "quetzal",
           "--workspace-name", "$(IGUAZU_WORKSPACE)",
    ]
dask_scheduler:
  name: dask-scheduler
  image:
    # repository: ... # use to override the default on iguazu.repository
    # tag: ...        # use to override the default on iguazu.tag
    pullPolicy: Always
  replicas: 1
  serviceType: ClusterIP  # Change to LoadBalancer if you want to access from outside (this is dangerous!)
  servicePort: 8786
  env:
    - name: PYTHONUNBUFFERED
      value: "1"
  resources: {}
    # limits:
    #   cpu: 1.8
    #   memory: 6G
    # requests:
    #   cpu: 1.8
    #   memory: 6G
  tolerations: []
  nodeSelector: {}
  affinity: {}

dask_worker:
  name: dask-worker
  image:
    # repository: ... # use to override the default on iguazu.repository
    # tag: ...        # use to override the default on iguazu.tag
    pullPolicy: Always
  replicas: 1         # Number of MINIMUM dask-workers
  maxReplicas: 4      # Number of MAXIMUM dask-workers
  targetCPU: 10       # How much the Horizontal scaler will target as CPU usage.
                      # When the average CPU is over this value, new workers will be creatd.
                      # Set to a low value (10) to use as much resources as possible.
  default_resources:  # overwritten by resource limits if they exist
    cpu: 1
    memory: "2GiB"
  env:
    - name: PYTHONUNBUFFERED
      value: "1"
  resources:
     limits:
       cpu: 1     # note: use integer (round values) here
       memory: 4G
     requests:
       cpu: 1
       memory: 4G
  tolerations: []
  nodeSelector: {}
  affinity: {}

quetzal:
  # Set these values with the URL, username and password used
  url: https://quetzal.omind.me/api/v1
  username: iguazu
  password:
  insecure: "0"

slack:
  url: "https://hooks.slack.com/services/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"
