{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $release_name := .Release.Name }}
{{- $app_name := include "iguazu.name" . -}}
{{- $full_name := include "iguazu.fullname" . -}}
{{- $default_job := .Values.defaultJob }}
{{- $iguazu_conf := .Values.iguazu}}

{{- range $job := .Values.jobs }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ $full_name }}-job-{{ $job.name }}"
  labels:
    app: {{ $app_name }}
    release: {{ $release_name }}
    chart: "{{ $chart_name }}-{{ $chart_version }}"
    component: cronjobs
spec:
  concurrencyPolicy: {{ $job.concurrencyPolicy | default $default_job.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ $job.failedJobsHistoryLimit | default $default_job.failedJobsHistoryLimit }}
  startingDeadlineSeconds: {{ $job.startingDeadlineSeconds | default $default_job.startingDeadlineSeconds }}
  schedule: {{ $job.schedule | quote }}
  successfulJobsHistoryLimit: {{ $job.successfulJobsHistoryLimit | default $default_job.successfulJobsHistoryLimit }}
  suspend: {{ $job.suspend | default $default_job.suspend }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ $app_name }}
            release: {{ $release_name }}
            component: cronjobs
        spec:
          containers:
          - image: "{{ $job.repository | default $iguazu_conf.repository }}:{{ $job.tag | default $iguazu_conf.tag}}"
            imagePullPolicy: {{ $job.pullPolicy | default $iguazu_conf.pullPolicy }}
            name: "job-{{ $job.name }}"
            env:
            {{- with $job.env | default $default_job.env }}
{{ toYaml . | indent 12 }}
            {{- end }}
            {{- range $secret_env := $job.envFromSecret | default $default_job.envFromSecret }}
            - name: {{ $secret_env.name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $full_name }}-secrets
                  key: {{ $secret_env.key }}
            {{- end }}
            {{- if $job.command }}
            command: {{ $job.command }}
            {{- end }}
            {{- with $job.args }}
            args:
{{ toYaml . | indent 12 }}
              {{- end }}
            {{- with $job.resources | default $default_job.resources }}
            resources:
{{ toYaml . | indent 14 }}
            {{- end }}
            {{- with $job.volumeMounts | default $default_job.volumeMounts }}
            volumeMounts:
{{ toYaml . | indent 12 }}
            {{- end }}
          {{- with $job.nodeSelector | default $default_job.nodeSelector}}
          nodeSelector:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with $job.affinity | default $default_job.affinity }}
          affinity:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with $job.tolerations | default $default_job.tolerations }}
          tolerations:
{{ toYaml . | indent 12 }}
          {{- end }}
          restartPolicy: {{ $job.restartPolicy | default $default_job.restartPolicy }}
          {{- with $job.volumes | default $default_job.volumes }}
          volumes:
{{ toYaml . | indent 12 }}
          {{- end }}
{{- end }}
