{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $release_name := .Release.Name }}
{{- $app_name := include "iguazu.fullname" . -}}

{{- range $job := .Values.jobs }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ $app_name }}-job-{{ $job.name }}"
  labels:
    app: {{ $app_name }}
    release: {{ $release_name }}
    chart: "{{ $chart_name }}-{{ $chart_version }}"
    component: cronjobs
spec:
  concurrencyPolicy: {{ $job.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ $job.failedJobsHistoryLimit }}
  startingDeadlineSeconds: {{ $job.startingDeadlineSeconds }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ $app_name }}
            release: {{ $release_name }}
            component: cronjobs
        spec:
          containers:
          - image: "{{ default $.Values.iguazu.repository $job.image.repository }}:{{ default $.Values.iguazu.tag $job.image.tag }}"
            imagePullPolicy: {{ $job.image.pullPolicy }}
            name: "job-{{ $job.name }}"
            {{- with $job.env }}
            env:
{{ toYaml . | indent 12 }}
            {{- end }}
            {{- range $secret_env := $job.envFromSecret }}
            - name: {{ $secret_env.name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $app_name }}-secrets
                  key: {{ $secret_env.key }}
            {{- end }}
            {{- if $job.command }}
            command: {{ $job.command }}
            {{- end }}
            {{- with $job.args }}
            args:
{{ toYaml . | indent 12 }}
              {{- end }}
            {{- with $job.resources }}
            resources:
{{ toYaml . | indent 14 }}
            {{- end }}
            {{- with $job.volumeMounts }}
            volumeMounts:
{{ toYaml . | indent 12 }}
            {{- end }}
          {{- with $job.nodeSelector }}
          nodeSelector:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with $job.affinity }}
          affinity:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with $job.tolerations }}
          tolerations:
{{ toYaml . | indent 12 }}
          {{- end }}
          restartPolicy: {{ $job.restartPolicy }}
          {{- with $job.volumes }}
          volumes:
{{ toYaml . | indent 12 }}
          {{- end }}
  schedule: {{ $job.schedule | quote }}
  successfulJobsHistoryLimit: {{ $job.successfulJobsHistoryLimit }}
  suspend: {{ $job.suspend }}
{{- end }}
