apiVersion: v1
kind: Service
metadata:
  name: dask-scheduler
  labels:
    app: {{ template "iguazu.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "iguazu.chart" . }}
    component: dask-scheduler
spec:
  ports:
    - name: dask-scheduler
      port: 8786
      targetPort: 8786
    - name: dask-ui
      port: 8787
      targetPort: 8787
  selector:
    app: {{ template "iguazu.name" . }}
    release: {{ .Release.Name | quote }}
    component: dask-scheduler
  type: {{ .Values.dask_scheduler.serviceType }}
