apiVersion: v1
kind: Service
metadata:
  name: {{ template "iguazu.fullname" . }}-dask-scheduler
  labels:
    app: {{ template "iguazu.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "iguazu.chart" . }}
    component: dask-scheduler
spec:
  ports:
    - name: {{ template "iguazu.fullname" . }}-dask-scheduler
      port: {{ .Values.dask_scheduler.servicePort }}
      targetPort: 8786
    - name: {{ template "iguazu.fullname" . }}-webui
      port: {{ .Values.dask_scheduler_ui.servicePort }}
      targetPort: 8787
  selector:
    app: {{ template "iguazu.name" . }}
    release: {{ .Release.Name | quote }}
    component: dask-scheduler
  type: {{ .Values.dask_scheduler.serviceType }}
