apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "iguazu.fullname" . }}-ingress
  annotations:
    # Note: Get full configuration annotations on
    # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: dask-scheduler
              servicePort: 8787
