apiVersion: v1
kind: Secret
metadata:
  name: {{ template "iguazu.fullname" . }}-secrets
  labels:
    app: {{ template "iguazu.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "iguazu.chart" . }}
    component: secrets
type: Opaque
stringData:
  username: {{ required "A valid .Values.quetzal.username is required!" .Values.quetzal.username | quote }}
  password: {{ required "A valid .Values.quetzal.password is required!" .Values.quetzal.password | quote }}
  slack_url: {{ .Values.slack.url | quote }}
