apiVersion: v1
kind: Secret
metadata:
  name: {{ template "iguazu.fullname" . }}-secrets
  labels:
    app: {{ template "iguazu.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "iguazu.chart" . }}
    component: secrets
type: Opaque
stringData:
{{/*  username: user*/}}
{{/*  password: pass*/}}
