name: unit tests
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Configure access token
      # This step needs to add a secret named "ACCESS_TOKEN" on
      # https://github.com/OpenMindInnovation/iguazu/settings/secrets
      # With the value from a token generated at
      # https://github.com/settings/tokens/new
      run: |
        git config --global --add url."https://${{ secrets.ACCESS_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
        git config --global --add url."https://${{ secrets.ACCESS_TOKEN }}:x-oauth-basic@github.com/".insteadOf "git@github.com:"

    - name: Install dependencies
      env:
        # Python-related environment variables
        PYTHONUNBUFFERED: "1"
        # prevents python creating .pyc files
        PYTHONDONTWRITEBYTECODE: "1"
        # pip-related environment variables
        PIP_NO_CACHE_DIR: "off"
        PIP_DISABLE_PIP_VERSION_CHECK: "on"
        PIP_DEFAULT_TIMEOUT: "100"
        PIP_VERSION: "20.0.2"
        # poetry-related environment variables
        # https://python-poetry.org/docs/configuration/#using-environment-variables
        POETRY_VERSION: "1.0.5"
        # make poetry install to this location
        POETRY_HOME: "/opt/poetry"
        # make poetry create the virtual environment in the project's root
        # it gets named `.venv`
        POETRY_VIRTUALENVS_IN_PROJECT: "true"
        # do not ask any interactive question
        POETRY_NO_INTERACTION: "1"
        # paths-related environment variables
        # this is where our requirements + virtual environment will live
        PYSETUP_PATH: "/opt/pysetup"
        VENV_PATH: "/opt/pysetup/.venv"
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
        export PATH="$POETRY_HOME/bin:$VENV_PATH/bin:$PATH"
        poetry install

    - name: Test with pytest
      env:
        VENV_PATH: "/opt/pysetup/.venv"
      run: |
        export PATH="$VENV_PATH/bin:$PATH"
        pytest -v
