name: unit tests
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Configure access token
      # This step needs to add a secret named "ACCESS_TOKEN" on
      # https://github.com/OpenMindInnovation/iguazu/settings/secrets
      # With the value from a token generated at
      # https://github.com/settings/tokens/new
      run: |
        git config --global --add url."https://${{ secrets.ACCESS_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
        git config --global --add url."https://${{ secrets.ACCESS_TOKEN }}:x-oauth-basic@github.com/".insteadOf "git@github.com:"

    - name: Install dependencies
      # Note that there is sed -ie to change from git+ssh to git+https because
      # our Docker image requires git, but the github workflow requires https
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
        poetry install

#     - name: Lint with flake8
#       run: |
#         pip install flake8
#         # stop the build if there are Python syntax errors or undefined names
#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest -v
